### ISSUE TITLE
IFD: ensurePath before dispatching as an optimization

### ISSUE THREAD

**Issue by domenkozar** [hercules-ci/hercules-ci-agent#128]
First evaluation with IFD will be slow regardless of this optimization, but
after that we can `ensurePath` to speed it up.

**Comment by roberth** [comment]
Specifically, we can make/keep the BuildRequired event asynchronous, not wait for a BuildResult and continue immediately. BuildRequest logic moves to the ensurePath exception handler.

**Comment by domenkozar** [comment]
This is now going to be tricky after #162, since we don't want to populate caches with negative entries.

Probably best to focus effort into concurrent IFD.

**Comment by domenkozar** [comment]
Going to close for now.
