### ISSUE TITLE
Switch to min-free max-free gc

### ISSUE THREAD

**Issue by roberth** [hercules-ci/hercules-ci-agent#150]
This makes GC time independent.
May or may not impact our testing with multiple stores on a single filesystem.
https://nixos.org/nix/manual/#conf-min-free

**Comment by domenkozar** [comment]
This will add build time to random derivations (I suppose?), not sure that's what we want.

**Comment by roberth** [comment]
Such "background GC" is already a thing, but it will be more common with this.
We can implement both. Time-based trigger to avoid background gc by liberally freeing up space "at night", but also background gc in cases we need it.

Alternatively, this type of GC may be more incremental and therefore much much harder to notice.

To be sure, we need experimental validation, but in any case, enabling should make out-of-disk virtually a thing of the past.
