### ISSUE TITLE
Agent: configurable work directory

### ISSUE THREAD

**Issue by domenkozar** [hercules-ci/hercules-ci-agent#173]

**Comment by roberth** [comment]
This has been available for some time now.

Deployments with module >= 0.8 (currently unreleased) or NixOS: [`settings.workDirectory`](https://search.nixos.org/options?show=services.hercules-ci-agent.settings.workDirectory&query=hercules%20ci&from=0&size=30&sort=relevance&channel=unstable) or `extraOptions.workDirectory`
For manually deployed config file and for reference: https://docs.hercules-ci.com/hercules-ci/reference/agent-config/#workDirectory
