### ISSUE TITLE
Upgrade to latest version causes effectiveConfig missing error.

### ISSUE THREAD

**Issue by jappeace** [hercules-ci/hercules-ci-agent#279]
**Description**
When trying to upgrade to the latest version from master we get the following error:

```
error: attribute 'effectiveConfig' missing, at /nix/store/5vx4p3n46p7r47s33aswgm7j8nqvn1br-source/internal/nix/deploy-keys.nix:6:22
```

**To Reproduce**

Upgrade from d3417d64fc128cef13d764f33829a80aa593da9f to f87aea13c6c854bceacf95fe98e4b3ac8b46639a

**Expected behavior**

It deploys or tells me what configuration I should change.

**Logs**

**Platform / Version**

![image](https://user-images.githubusercontent.com/3874017/109048237-3aa14780-76ad-11eb-9e08-5794c1991716.png)

Best to go to https://hercules-ci.com/dashboard and click on the agents' tab for the account you're interested in.
**hercules-ci-agent --help** version

**Comment by roberth** [comment]
#281 fixes this error and evaluates on the example configuration from the setup guide without errors.

**Comment by jappeace** [comment]
This is fixed for us now.
