### ISSUE TITLE
Running an effect causes a permission denied error

### ISSUE THREAD

**Issue by jappeace** [hercules-ci/hercules-ci-agent#292]
**Description**
Running an effect causes a permission denied error

![image](https://user-images.githubusercontent.com/3874017/112879749-92114980-9097-11eb-9765-845670d5343c.png)

I'm not sure what happened but today it no longer evaluates effects. Fortunately it's still on a branch so I'm just keeping the effect seperate for now.

**To Reproduce**
Run an effect.

**Expected behavior**
The effect evaluates.

**Logs**

**Platform / Version**

Best to go to https://hercules-ci.com/dashboard and click on the agents' tab for the account you're interested in.

![image](https://user-images.githubusercontent.com/3874017/112880076-fc29ee80-9097-11eb-9dc1-74ac8bd948b7.png)

```
[jappie@agent:/etc]$ cat agent-version 
https://github.com/hercules-ci/hercules-ci-agent/archive/7fc025e183f22a21360b550dc0d0e15a5c1a3122.tar.gz
```

**Comment by roberth** [comment]
I'm looking into it.

**Comment by roberth** [comment]
@jappeace I've merged a fix.

**Comment by jappeace** [comment]
Thanks for your timely response, this is solved now.
