### ISSUE TITLE
Worker failed with exit status -6

### ISSUE THREAD

**Issue by jappeace** [hercules-ci/hercules-ci-agent#294]
**Description**
I got this error when testing a new keter based configuration.
There should be more expressions after it, but it stopped evaluating them all after the error.
After pressing rebuild it stopped being an issue. (so this maybe a one-off issue?)

![image](https://user-images.githubusercontent.com/3874017/113207198-54025a00-923e-11eb-923a-51674182c72b.png)

**To Reproduce**
I don't know. Doing another run worked.

**Expected behavior**
Don't fail with exit status -6.

**Logs**

**Platform / Version**

![image](https://user-images.githubusercontent.com/3874017/113207727-f6224200-923e-11eb-832f-9295600862aa.png)

This is the agent version string:
```
https://github.com/hercules-ci/hercules-ci-agent/archive/4110b97734d54dc0df22e6e01a426038e236d710.tar.gz
```

**Comment by roberth** [comment]
Possibly a duplicate of #182. These seem to be rare, so I will investigate further if you encounter it again.

**Comment by jappeace** [comment]
Ok ok, if I ever see it again I'll mention it in #182
