### ISSUE TITLE
Darwin support?

### ISSUE THREAD

**Issue by kreisys** [hercules-ci/hercules-ci-agent#31]
I see that `default.nix` only refers to the `nixos-*` branches.
It's pretty common for devs to have a darwin workstation while production instances run NixOS. Would be beneficial to be able to provide binary caches for darwiners as well.
Would that be feasible?

Cheers

**Comment by roberth** [comment]
Multiple agents and multiple architectures are not officially supported at this time.
They are on the roadmap: https://github.com/hercules-ci/support/issues/6, https://github.com/hercules-ci/support/issues/4

**Comment by domenkozar** [comment]
@kreisys we've been working on this in the last couple of weeks and it's almost here.

- [compile agent on Darwin](https://github.com/hercules-ci/hercules-ci-agent/pull/55)
- [cachix support](https://github.com/hercules-ci/hercules-ci-agent/pull/52)

What's missing is agent release and good documentation on how to set the agent on Darwin.

We'll then setup binary cache to speed this up.

**Comment by domenkozar** [comment]
Darwin is now supported as part of https://github.com/hercules-ci/hercules-ci-agent/releases/tag/hercules-ci-agent-0.3.0, we'll publish a blog post on https://blog.hercules-ci.com/ and announce to preview subscribers.
