### ISSUE TITLE
Document how to use the NixOS module by itself

### ISSUE THREAD

**Issue by domenkozar** [hercules-ci/hercules-ci-agent#33]
At the moment we only support NixOps deployment, while someone might want to use just NixOS module (maybe with terraform or such).

**Comment by roberth** [comment]
Or `profile.nix` which includes better defaults like turning on automatic garbage collection.

**Comment by domenkozar** [comment]
@nh2 didn't want to use nixops so this part seems crucial to document. It's complicated due to binary cache setup at the moment.

**Comment by domenkozar** [comment]
> That one is relatively important to me. I think submodules are better than niv for situations where you iterating on a project also requires iterating on nixpkgs (or dependency projects in general). Where in the agent code do you clone the repo? If it's just a simple `git clone`, it will be enough to just add the `--recursive` flag

**Comment by domenkozar** [comment]
done https://docs.hercules-ci.com/hercules-ci/getting-started/deploy/nixos/
