### ISSUE TITLE
`aarch64` support?

### ISSUE THREAD

**Issue by dhess** [hercules-ci/hercules-ci-agent#336]
Hi @roberth, does the agent (and/or the service) support `aarch64-{darwin,linux}` yet?

**Comment by roberth** [comment]
`aarch64-linux` has been available for over a year with no arch-specific issues.
I haven't tested the agent on `aarch64-darwin` yet, but it [is already buildable there](https://hydra.nixos.org/jobset/nixpkgs/nixpkgs-unstable-aarch64-darwin#tabs-jobs). I'll test it out and add it to the CI.

**Comment by roberth** [comment]
There's one known issue https://github.com/hercules-ci/hercules-ci-agent/issues/231#issuecomment-970678587, so certain misconfigurations, like inability to pull a _derivation_ from the shared cache, will manifest as `Worker failed with exit status -6` instead of a helpful error message.

**Comment by dhess** [comment]
Thanks!
