### ISSUE TITLE
NixOS w/ flakes: error: in pure evaluation mode, 'fetchTarball' requires a 'sha256' argument

### ISSUE THREAD

**Issue by srid** [hercules-ci/hercules-ci-agent#341]
I configure my NixOS using Flakes. First, I added the agent as a flake input:

```nix
    hercules-ci-agent = {
      url = "github:hercules-ci/hercules-ci-agent/stable";
      flake = false;
    };
```

(It doesn't matter if the flake flag is true or not)

And then used it from my declarative container config as follows:

```nix
      imports = [
        (inputs.hercules-ci-agent + "/module.nix")
      ];
      services.hercules-ci-agent.enable = true;
      services.hercules-ci-agent.concurrentTasks = 4;

```

Running `nixes-rebuild switch` threw:

```
sudo nixos-rebuild switch -j auto 
warning: Git tree '/etc/nixos' is dirty
building the system configuration...
warning: Git tree '/etc/nixos' is dirty
error: in pure evaluation mode, 'fetchTarball' requires a 'sha256' argument
(use '--show-trace' to show detailed location information)
```

**Comment by srid** [comment]
Log with trace: https://gist.githubusercontent.com/srid/0ebd0325b00e7e65520b36b8c46022a0/raw/802ccd516af8ff837175fa8a625104900514ef2a/gistfile1.txt

**Comment by srid** [comment]
For the record, same issue when using fetchTarball:

```nix
      imports = [
        # (inputs.hercules-ci-agent + "/module.nix")
        (builtins.fetchTarball
          {
            url = "https://github.com/hercules-ci/hercules-ci-agent/archive/ecac058b7633f969350cbc22e8c8a7466bcbc13f.tar.gz";
            sha256 = "sha256-I7Npzb0Zf58b68o1FDDphg2FsHp/V/Jhub3DzSXIBE4=";
          }
        + "/module.nix"
        )
      ];
      services.hercules-ci-agent.enable = true;
      services.hercules-ci-agent.concurrentTasks = 4;
```

**Comment by roberth** [comment]
I've tried to support this style of import, but it can't be done with Nix 2.4. You'll really have to use

```nix
{
  imports = [
     inputs.hercules-ci-agent.nixosModules.agent-service
  ];
```

#342 will give a hint, but as said, there's not much else that can be done. Nix 2.4 broke flake-compat too and it can't re-import a flake from a path. :(

**Comment by srid** [comment]
@roberth I see, thanks!

I'm installing the agent in a declarative container, https://nixos.wiki/wiki/NixOS_Containers ... I do not know if that supports flakes, let me go down that path. Thanks for the hint.
