### ISSUE TITLE
Running agent inside NixOS container

### ISSUE THREAD

**Issue by srid** [hercules-ci/hercules-ci-agent#345]
Is it supported to run the agent inside a NixOS container? https://nixos.wiki/wiki/NixOS_Containers

For me the agent is crashing with this error:

```
   Exception: cannot open connection to remote store 'daemon': reading from file: Connection reset by peer; type: nix::Error
```

Which presumably is something to do with container perms (nix daemon not exposed to container?).

**Comment by roberth** [comment]
Looking at the NixOS containers, it should be possible, in theory.

What's the Nix configuration on the host? Specifically, `grep user /etc/nix/nix.conf`?


------

Notes to self:

It seems likely that the agent will have to run as a client that is not trusted by the daemon. A Nix client can not discover this properly, so this will need

```nix
    services.hercules-ci-agent.settings.nixUserIsTrusted = lib.mkForce false;
```

Perhaps the module could detect being in a container. There's `boot.isContainer`, but that may not be unique to _NixOS_ containers.

**Comment by srid** [comment]
`/etc/nix/nix.conf` on host contains:

```
build-users-group = nixbld
trusted-users = root srid
allowed-users = root srid
```

Note that `/nix/var/nix/daemon-socket/socket` is available on the container guest.

**Comment by srid** [comment]
Changed to return:

```
trusted-users = root srid hercules-ci-agent
allowed-users = root srid root srid hercules-ci-agent
```

Still no luck.

**Comment by roberth** [comment]
Probably `nix-daemon` doesn't recognize the (mapped?) uid of the client in the container.
Unless you can somehow pin the uid or gid so that it is stable from the host perspective, you may have to allow all users.

```
allowed-users = *
```

>        • allowed-users
> 
>          A list of names of users (separated by whitespace) that are allowed to connect to the Nix daemon. As with the trusted-users option, you can specify groups by prefixing them with @. Also, you can allow all users by specifying *. The default is *.
> 
>          Note that trusted users are always allowed to connect.
> 
>          Default: *

**Comment by srid** [comment]
Ah, yes. Also I had allowedUsers being set from elsewhere (harden.nix). Okay, `*` works for now. Thanks @roberth - should I leave this issue open, or is there an action item to add this to the FAQ or documentation? I imagine users might want to run the agent in the container for security (to keep it separate from the rest of the sensitive stuff on the host), while trust the Nix daemon to behave well that is.

https://github.com/srid/nixos-config/blob/master/containers/hercules.nix

**Comment by roberth** [comment]
Let's keep it open. A solution without `allowed-users = *` seems possible, using a dumb proxy that runs on the host. That would allow only the listed users and user-configured containers to access the daemon.

Also note that you have to do the same thing for `trusted-users = *`, or in the container set

```
    services.hercules-ci-agent.settings.nixUserIsTrusted = lib.mkForce false;
```

The latter choice comes at the cost of having to download derivation closures when using multiple agents.

**Comment by srid** [comment]
> The latter choice comes at the cost of having to download derivation closures when using multiple agents.

Hmm, not sure I understand this. When `nixUserIsTrusted` is false, does the agent not use the host's nix store (thus being able to use its store cache)?

**Comment by srid** [comment]
Aside: hmm, looks like it? It is building lot of packages: https://hercules-ci.com/github/srid/haskell.page/jobs/6

**Comment by roberth** [comment]
When `hercules-ci-agent` is not trusted by the daemon, it needs to do more, to prove that what it wants to build is a valid _derivation_ closure. That's not the case when it is trusted.
Normally the module sets up trust and you don't have to worry about it.

**Comment by roberth** [comment]
> It is building lot of packages:

Cached packages currently follow more of the regular build flow than strictly necessary. Some latency can be saved.

**Comment by roberth** [comment]
While technically nothing should prevent this from working, NixOS containers seem to be broken. An alternative solution for running multiple agents is a new module. See #361
