### ISSUE TITLE
Get rid of servant-streaming and use a single build of the functional tests

### ISSUE THREAD

**Issue by roberth** [hercules-ci/hercules-ci-agent#35]
Blocks this update
https://hercules-ci.com/github/hercules-ci/hercules-ci-agent/jobs/92

This is also a good opportunity to build the functional tests only on the most recent haskell package set and reuse that derivation for the other versions of nixos that we test.

**Comment by domenkozar** [comment]
You can use servant 0.15 streaming instead. See https://github.com/cachix/cachix/commit/0d39a822355c808813a2bebe1ad34caad46b14cf#diff-f8bfc0a8788d74564244c156646023b9R67
