### ISSUE TITLE
Effects do not work in NixOS Containers

### ISSUE THREAD

**Issue by MatthewCroughan** [hercules-ci/hercules-ci-agent#361]
This applies to both cgroupsv1 and cgroupsv2. 

### Failure logs
- cgroupsv1 https://hercules-ci.com/github/Plutonomicon/plutonomicon/jobs/8/effects/effects.helloWorld/log
- cgroupsv2 https://hercules-ci.com/github/Plutonomicon/plutonomicon/jobs/7/effects/effects.helloWorld/log

The NixOS container in which the agent is running is defined in code here:
https://github.com/MatthewCroughan/nixcfg/blob/f7ce5f6/hosts/swordfish/modules/hercules-ci-agent.nix#L34-L63

As workarounds, I have tried adding all capabilities to the container, as well as setting `Delegate = "cpu cpuset io memory pids"` in the `serviceConfig` of the container service, like `systemd.services."container@plutonomicon-swordfish.service".serviceConfig.Delegate = "cpu cpuset io memory pids";` for example. I have also tried `Delegate = "yes"`.

Inside of the NixOS container, I have tried setting `virtualisation.podman.enable = true;` and playing around to see what can and cannot be done. I found the following:

```
[root@plutonomicon-swordfish:~]# podman run hello-world
Your kernel does not support pids limit capabilities or the cgroup is not mounted. PIDs limit discarded.
Error: OCI runtime error: cannot find memory or pids controller for the current process

[root@plutonomicon-swordfish:~]# podman run hello-world --cgroup-manager cgroupfs
Your kernel does not support pids limit capabilities or the cgroup is not mounted. PIDs limit discarded.
Error: OCI runtime error: cannot find memory or pids controller for the current process
```

I have also tried setting `extraFlags = [ "-E SYSTEMD_SECCOMP=0" ];` for the container.

**Comment by roberth** [comment]
This is a problem of `runc` interacting with `systemd-nspawn`, which I can't realistically solve in this project.
Effects do run in NixOS-based containers inside Podman, also suggesting that this is beyond the project's control.

However, if the goal is to run multiple agents on one system, you can now make use of a new module in the flake. To quote the changelog:

 - The flake now has `.nixosModules.multi-agent-service` allowing multiple agents
   to run on the same system.
   An instance with default settings can be enabled with `services.hercules-ci-agents."some-name" = {}`.
   User name and file paths are like the regular module, except replacing `hercules-ci-agent` by `hci-${name}` if the chosen `name` is not `""`.
   `services.hercules-ci-agents."" = {}` is equivalent to `services.hercules-ci-agent.enable = true`.

More extensive documentation is to be done (#366)
