### ISSUE TITLE
Provide sample repo for usage with `runNixOps2` and flakes

### ISSUE THREAD

**Issue by nmauersberg** [hercules-ci/hercules-ci-agent#369]
Hi!
We would really much appreciate a sample repository for using the [`runNixOps2`](https://docs.hercules-ci.com/hercules-ci-effects/reference/nix-functions/runnixops2/) API with nix flakes. Currently the only sample is given for [`runNixOps`](https://docs.hercules-ci.com/hercules-ci-effects/reference/nix-functions/runnixops/): https://docs.hercules-ci.com/hercules-ci/getting-started/minimal-repository/

Does something like this exist somewhere?
Kind regards and thank you!

**Comment by roberth** [comment]
Will create this.

**Comment by roberth** [comment]
Here's an example repo https://github.com/hercules-ci/nixops2-flake

I went 100% flake with it, which currently limits the ability to create multiple networks, as you might for a staging environment for example. This means that adding, say, a staging environment is currently non-trivial, but I can do it by avoiding nixops' built-in flake support. Do you need multiple deployments like that?

**Comment by nmauersberg** [comment]
@roberth Thank you very much! That's a great starting point. We will need a deployment with a staging environment very soon, but we'll see how we get along with that. I will keep you updated how it works out and if other questions come up. For the moment we have to focus on some core features of our project, and we have got a "working" deployment pipeline right now, even if it's not green right now. Hopefully we'll be able to tackle that next week.

Btw, it's really cool stuff you were building. The UI is snappy and so reliable, thank you for your work.

**Comment by thought2** [comment]
@roberth Thanks for the sample repo. We're finally using the same approach in our project and it works really well on hercules!

Today I wanted to try if I can also run the checks locally with `nix flake check`. When I checkout your repo it works. But after some crazy debugging I found out that it breaks when `deployment.targetHost` is used instead of `deployment.targetEnv`. Which is the case in our situation.

This is the error I'm getting:
```
error: attribute 'currentSystem' missing

       at /nix/store/m7rkvylwvmkdm109ayv295006a8kvx9h-source/nixos/lib/eval-config.nix:13:12:

           12| { # !!! system can be set modularly, would be nice to remove
           13|   system ? builtins.currentSystem
             |            ^
           14| , # !!! is this argument needed any more? The pkgs argument can
(use '--show-trace' to show detailed location information)
```

Do you have any idea what we can do here?

**Comment by roberth** [comment]
@thought2 You can probably fix this by setting `nixpkgs.system` for that host, as there's no `targetEnv` plugin that can set it for you.

It'd be nice for NixOps to emit an understandable message in this scenario.

**Comment by thought2** [comment]
Great. That was it! Thanks a lot for the fast reply.
