### ISSUE TITLE
`<store path> does not exist and cannot be created` when store path exists

### ISSUE THREAD

**Issue by getchoo** [hercules-ci/hercules-ci-agent#513]
**Description**
recently i've added an aarch64 vps to my group of agents. after a bit of messing around, i pushed some commits to trigger ci runs, which have led me to the error printed below.

i would think this just needs another rebuild, but after finding that the store path *did* exist and [multiple](https://hercules-ci.com/github/getchoo/flake/jobs/76) [other](https://hercules-ci.com/github/getchoo/flake/jobs/77) attempts, i think this could be a bug. 

for reference, here is my [flake](https://github.com/getchoo/flake) containing the system configuration for the agent itself (see [`hosts/atlas/default.nix`](https://github.com/getchoo/flake/blob/604f9495b8191644f2334e9b2cf28407bab6d428/hosts/atlas/default.nix) specifically), along with the ci configuration in `flake.nix`

**To Reproduce**
- evaluate `nixosConfigurations.atlas.config.build.system.top-level` on [604f949](https://github.com/getchoo/flake/tree/604f9495b8191644f2334e9b2cf28407bab6d428)

**Expected behavior**

`/nix/store/86mxvrk64kkk9l0hpzs91xd2lb0359v8-cabal2nix-cabal-pkg-config-version-hook` is found correctly and evaluation is successful

**Logs**
```
querying info about missing paths


```

```
Message: error: Build failure: output could not be retrieved on the evaluating agent, despite a successful rebuild.
Exception: CppStdException e "\ESC[31;1merror:\ESC[0m path '\ESC[35;1m/nix/store/86mxvrk64kkk9l0hpzs91xd2lb0359v8-cabal2nix-cabal-pkg-config-version-hook\ESC[0m' does not exist and cannot be created"(Just "nix::Error")
```

**Platform / Version**
aarch64-linux/v0.9.11

**Comment by roberth** [comment]
Is it configured to push to a cache that the evaluating `x86_64-linux` agent pulls from? (or pushes to; push implies also pull in agent config)

Agents by default rely on the cache to for the copying of store paths. Alternatively, you could configure the workers as ssh substituters on the evaluating agent, but the extra substitution latency may not be worth it.

**Comment by getchoo** [comment]
no caches are being used right now, so i think i might try configuring the worker as an ssh substituter

**Comment by roberth** [comment]
Configuration changes and restarts aren't handled very well yet. You might work around this by restarting the job so that `.drv` files are pushed, wait for the evaluation phase to complete, then restart again to clear derivation restarts that may have occurred too soon.

**Comment by getchoo** [comment]
after restarting multiple times after evaluation, i'm still getting the same issue. i tried a new pushing a new commit as well but no dice

**Comment by getchoo** [comment]
forgot to close this, apologies
