### ISSUE TITLE
nixops: rename deployment.keys."agent-token.key" to something hercules-specific

### ISSUE THREAD

**Issue by flokli** [hercules-ci/hercules-ci-agent#54]
When deploying hercules-ci with NixOps, `deployment.keys."agent-token.key"` needs to be set.
This name is a bit confusing, as it's generic and doesn't show it is hercules-ci-related at all. Could this be renamed to something like `deployment.keys."hercules-ci-agent-token"`?

The secret [is copied to `"/var/lib/keys/hercules-ci-agent"` anyhow](https://github.com/hercules-ci/hercules-ci-agent/blob/master/for-upstream-only/nixos/profiles/nixops-hercules-ci-agent.nix#L15), so the name shouldn't matter much, except provide some information to the user ;-)

**Comment by domenkozar** [comment]
FYI: it's now called `cluster-join-token.key`

**Comment by roberth** [comment]
NixOS >= 20.09 has a module that doesn't take ownership of NixOps key deployment. This style of module will also be available in the repo for those who want a newer version of hercules-ci-agent.

**Comment by roberth** [comment]
You can use `nixosModules.agent-service` in the flake or use the module from Nixpkgs to define your own nixops key uploads.
