### ISSUE TITLE
worker exception on Darwin during evaluation

### ISSUE THREAD

**Issue by domenkozar** [hercules-ci/hercules-ci-agent#61]
```
worker: libc++abi.dylib: terminating with uncaught exception of type nix::TypeError: anonymous function at /private/var/folders/v_/wjr5c3kj39143hlp1339ynpm0000hm/T/hercules-ci-agent-5e380b916750d98d/primary/domenkozar-stack2nix-35def65/stack2nix.nix:16045:10 called without required argument 'CoreServices', at /nix/store/bgk396j3gbd05xhygzxckmymlf9k77lz-c21f08bfedde0f7d00a5ebc85455fb28b9037932.tar.gz-unpacked/pkgs/development/haskell-modules/make-package-set.nix:87:27
```

evaluating https://github.com/domenkozar/stack2nix master branch on a darwin worker.

similar for hercules-ci-agent repo itself:

```
worker: libc++abi.dylib: terminating with uncaught exception of type nix::AssertionError: assertion failed at /nix/store/58dqc1b0jksgkmv97b4xyr7cdy628521-source/pkgs/top-level/stage.nix:150:21
```

**Comment by domenkozar** [comment]
Seems to be an upstream bug: https://github.com/fpco/inline-c/pull/89

**Comment by roberth** [comment]
This will only affect users who want to run a darwin-only cluster, considering our earlier decision to always evaluate on linux for `currentSystem` determinism, at least for the near future. Not my favorite line of reasoning, but it does mean it's not an immediate problem for now. We'll have to fix it though.

**Comment by domenkozar** [comment]
inline-c-cpp-0.3.0.2 fixes this bug, but it needs to be re-tested.

**Comment by roberth** [comment]
We don't have a way for a project to configure where it evaluates, so to keep it deterministic we'll keep evaluation on Linux for now anyway. So no hurry.

**Comment by domenkozar** [comment]
Agreed.

**Comment by roberth** [comment]
Not relevant before https://github.com/hercules-ci/support/issues/24

**Comment by domenkozar** [comment]
I'm going to close this as it was fixed upstream, if it persists once we are doing evaluation on darwin, we can just reopen.
