### ISSUE TITLE
NixOS's nix and our pinned nix should match

### ISSUE THREAD

**Issue by roberth** [hercules-ci/hercules-ci-agent#67]
The should match or at least be compatible, so we know that it works.
It should to be a version that we build against, so that cachix can provide the prebuilt binary for the agent. Therefore, we should override it to the version we build against.

Means to this end:
 - set nix.package (may not affect whole system)
 - add our nix via overlay.nix (may not affect whole system either)

We should probably do both.

Open questions:
 - do we do it through module.nix or profile.nix?
 - do we let the user choose not to override nix to our version?

**Comment by domenkozar** [comment]
We don't pin Nix yet, so this will be needed once #32 is done

**Comment by domenkozar** [comment]
We've decided not to do that as daemon protocol is considered stable and backwards compatible (unless client is using new features that older daemon doesn't know about but that's should yield a nice error in Nix).
