### ISSUE TITLE
Move Dhall logic outside the agent.

### ISSUE THREAD

**Issue by roberth** [hercules-ci/hercules-ci-agent#73]
Currently hercules-ci-agent reads a dhall config file natively. Dhall is a nice source language for configuration, but not a well-supported target language. The agent is not using the powerful Dhall features like functions and probably doesn't need to.

We can simplify the configuration system by using dhall-to-json and make the agent read that JSON. This will enable other configuration systems to generate agent configuration more easily. For example, Nixpkgs doesn't currently have the functions to support Dhall generation at evaluation time.

This will allow `module.nix` to use a config file instead of command line options. We may then even get rid of command line argument altogether, except perhaps a config location argument.

**Comment by domenkozar** [comment]
Fixed in #73
