### ISSUE TITLE
Watch for new cluster join token and request new agent session token when changed

### ISSUE THREAD

**Issue by roberth** [hercules-ci/hercules-ci-agent#8]
This is a usability enhancement for redeploying agents to a different cluster without manual operations on the agent or destroying the agent machine.

# Problem

Changing cluster join token doesn't switch the agent to a different account.

# Workaround

`sudo rm /var/lib/hercules-ci-agent/secretState/session.key`

**Comment by domenkozar** [comment]
I found https://www.linux.com/blog/learn/intro-to-linux/2018/6/systemd-services-monitoring-files-and-directories, but actually, it should be systemd independent.

**Comment by domenkozar** [comment]
Merged to master.
